// @generated by hachimi-protocol. Do not edit.

// This file has been generated by Specta. Do not edit this file manually.
export type AppSettings = {
	schemaVersion: number,
	theme: ThemeMode,
	locale: Locale,
	alwaysOnTop: boolean,
	petPlacement: WindowPlacementV1 | null,
	llm: LlmSettings,
	voice: VoiceSettings,
	appearance: AppearanceConfig,
	/**  Enables developer-only Workbench surfaces after restart without changing schema 7. */
	developerMode?: boolean,
};

export type AppearanceConfig = {
	lightThemeId: string,
	darkThemeId: string,
	themes: ThemeProfile[],
	preferences: AppearancePreferences,
};

export type AppearancePreferences = {
	pointerCursor: boolean,
	reducedMotion: ReducedMotion,
	uiFontSize: number,
	codeFontSize: number,
	diffMarkers: DiffMarkerMode,
};

export type AvatarAdaptationProfile = {
	vrmVersion: AvatarFormat,
	bones: AvatarRestBone[],
	expressions: AvatarExpressionBinding[],
	lookAt: AvatarLookAtProfile,
	springBoneGroupCount: number,
	colliderCount: number,
	jointLimits: AvatarJointLimit[],
	proportions: AvatarBodyProportions,
	contacts: AvatarContactPoint[],
	collisionCapsules: AvatarCollisionCapsule[],
	leftKneePole: [(number | null), (number | null), (number | null)],
	rightKneePole: [(number | null), (number | null), (number | null)],
	leftElbowPole: [(number | null), (number | null), (number | null)],
	rightElbowPole: [(number | null), (number | null), (number | null)],
	lipSync: LipSyncCapability,
	hasFingerBones: boolean,
	hasToeBones: boolean,
};

export type AvatarAssessment = {
	compatibility: AvatarCompatibility,
	detectorVersion: number,
	capabilities: AvatarCapability[],
	statistics: AvatarStatistics,
	requirements: AvatarRequirementResult[],
	issues: AvatarIssue[],
};

export type AvatarBodyProportions = {
	height: number | null,
	shoulderWidth: number | null,
	hipWidth: number | null,
	spineLength: number | null,
	leftUpperArmLength: number | null,
	leftLowerArmLength: number | null,
	rightUpperArmLength: number | null,
	rightLowerArmLength: number | null,
	leftUpperLegLength: number | null,
	leftLowerLegLength: number | null,
	rightUpperLegLength: number | null,
	rightLowerLegLength: number | null,
	leftHandLength: number | null,
	rightHandLength: number | null,
	leftFootLength: number | null,
	rightFootLength: number | null,
	footHeight: number | null,
};

export type AvatarCapability = "renderable_mesh" | "skinned_mesh" | "built_in_animations" | "humanoid_skeleton" | "blink" | "viseme" | "look_at" | "happy_expression" | "sad_expression" | "angry_expression" | "spring_bone" | "standard_motion_retarget" | "runtime_ready" | "m_toon" | "spring_bone_collider" | "five_finger_hands" | "five_visemes" | "standard_expressions" | "lip_sync_jaw" | "lip_sync_five_viseme";

export type AvatarCatalogSnapshot = {
	entries: AvatarEntry[],
	currentId: string | null,
};

export type AvatarCollisionCapsule = {
	bone: string,
	radius: number | null,
	halfHeight: number | null,
};

export type AvatarCompatibility = "runtime_ready" | "incompatible";

export type AvatarContactPoint = {
	id: string,
	bone: string,
	localPosition: [(number | null), (number | null), (number | null)],
	localNormal: [(number | null), (number | null), (number | null)],
	radius: number | null,
};

export type AvatarEntry = {
	id: string,
	name: string,
	originalFileName: string,
	sizeBytes: number,
	sha256: string,
	importedAt: string,
	isCurrent: boolean,
	protected: boolean,
	format: AvatarFormat,
	assessment: AvatarAssessment,
};

export type AvatarExpressionBinding = {
	expression: string,
	nodeIndex: number,
	morphIndex: number,
};

export type AvatarFormat = "glb" | "vrm0" | "vrm1";

export type AvatarImportCommitRequest = {
	token: string,
	name: string,
};

export type AvatarImportInspection = {
	token: string | null,
	originalFileName: string,
	sizeBytes: number,
	sha256: string,
	format: AvatarFormat,
	assessment: AvatarAssessment,
};

export type AvatarIssue = {
	code: string,
	severity: AvatarIssueSeverity,
};

export type AvatarIssueSeverity = "info" | "warning" | "error";

export type AvatarJointLimit = {
	bone: string,
	swingDegrees: number | null,
	twistMinDegrees: number | null,
	twistMaxDegrees: number | null,
};

export type AvatarLookAtProfile = {
	eyeForwardAxis: [(number | null), (number | null), (number | null)],
	horizontalInnerDegrees: number | null,
	horizontalOuterDegrees: number | null,
	verticalUpDegrees: number | null,
	verticalDownDegrees: number | null,
};

export type AvatarRequirementResult = {
	requirement: string,
	passed: boolean,
	detail: string,
};

export type AvatarRestBone = {
	bone: string,
	nodeIndex: number,
	parentBone: string | null,
	localTranslation: [(number | null), (number | null), (number | null)],
	localRotation: [(number | null), (number | null), (number | null), (number | null)],
	length: number | null,
};

export type AvatarRuntimeAsset = {
	entryId: string,
	name: string,
	sha256: string,
	assetUrl: string,
	format: AvatarFormat,
	profile: AvatarAdaptationProfile,
};

export type AvatarStatistics = {
	nodeCount?: number,
	meshCount?: number,
	primitiveCount?: number,
	triangleCount?: number,
	materialCount?: number,
	textureCount?: number,
	boneCount?: number,
	animationCount?: number,
	morphTargetCount?: number,
	maxTextureDimension?: number,
	estimatedTextureMemoryBytes?: number,
};

export type BehaviorChannel = "root" | "locomotion" | "full_body" | "lower_body" | "upper_body" | "left_arm" | "right_arm" | "fingers" | "head" | "gaze" | "face" | "mouth" | "spring";

export type BootstrapState = {
	protocolVersion: number,
	windowKind: WindowKind,
	locale: Locale,
	theme: ThemeMode,
	appearance: AppearanceConfig,
	alwaysOnTop: boolean,
	featureFlags: FeatureFlags,
};

export type ClientId = string;

export type ClipMotionRequest = {
	requestId: string,
	motionId: string,
	active: boolean,
	priority: number,
	mirror: boolean,
	channelWeights: MotionChannelWeight[],
};

export type ControlError = {
	code: ControlErrorCode,
	message: string,
};

export type ControlErrorCode = "invalid_protocol_version" | "invalid_request" | "unknown_method" | "permission_denied" | "approval_required" | "feature_disabled" | "conflict" | "internal";

export type DiffMarkerMode = "color" | "signs";

export type FeatureFlags = {
	workbench: boolean,
	motionLab: boolean,
	workspaceTools: boolean,
	browserControl: boolean,
	computerObserve: boolean,
	computerControl: boolean,
	remoteTts: boolean,
	remoteGateway: boolean,
	connectorPlugins: boolean,
};

export type FrontendLogEntry = {
	level: FrontendLogLevel,
	message: string,
};

export type FrontendLogLevel = "info" | "warn" | "error";

export type InteractionMotionBinding = {
	region: InteractionRegion,
	motionId: string,
	cooldownMs: number,
	mirrorBySide: boolean,
};

export type InteractionMotionBindingUpdateRequest = {
	region: InteractionRegion,
	motionId?: string | null,
	cooldownMs?: number | null,
	mirrorBySide?: boolean | null,
};

export type InteractionMotionPreviewRequest = {
	region: InteractionRegion,
};

export type InteractionRegion = "head_top" | "face" | "chest" | "belly" | "hips" | "left_hand" | "right_hand" | "left_arm" | "right_arm" | "left_leg" | "right_leg" | "foot" | "generic";

export type InteractiveRegionsUpdate = {
	windowLabel: string,
	revision: number,
	windowWidth: number | null,
	windowHeight: number | null,
	regions: LogicalRect[],
};

export type LipSyncCapability = "none" | "jaw" | "five_viseme";

export type LlmSettings = {
	baseUrl: string,
	modelName: string,
	maxInputTokens: number,
	maxOutputTokens: number,
};

export type LlmSettingsInput = {
	baseUrl: string,
	modelName: string,
	maxInputTokens: number,
	maxOutputTokens: number,
	/**  Missing or blank keeps the existing secret. Secrets are never returned to the WebView. */
	apiKey: string | null,
	clearApiKey: boolean,
};

export type LlmSettingsView = {
	baseUrl: string,
	modelName: string,
	maxInputTokens: number,
	maxOutputTokens: number,
	apiKeyConfigured: boolean,
};

export type LlmTestResult = {
	success: boolean,
	latencyMs: number,
	responsePreview: string,
};

export type Locale = "zh-CN" | "en-US";

export type LogicalRect = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

export type MotionAssetBindingsClearRequest = {
	motionId: string,
};

export type MotionBindingResetRequest = {
	region: InteractionRegion,
};

export type MotionCatalogEntry = {
	id: string,
	source: MotionSource,
	protected: boolean,
	name: string,
	nameZh?: string,
	description: string,
	descriptionZh?: string,
	fileName: string,
	sha256: string,
	sizeBytes: number,
	durationMs: number,
	category: MotionCategory,
	tags: string[],
	playbackMode: MotionPlaybackMode,
	rootMode: MotionRootMode,
	channels: BehaviorChannel[],
	animatedBones: string[],
	fingerBoneCount: number,
	hasFingerMotion: boolean,
	hasExpression: boolean,
	hasLookAt: boolean,
	mirrorable: boolean,
	transitionInMs: number,
	transitionOutMs: number,
	sourceProject: string,
	sourcePaths: string[],
	warnings?: string[],
};

export type MotionCatalogSnapshot = {
	entries: MotionCatalogEntry[],
	bindings: InteractionMotionBinding[],
	disabledMotionIds: string[],
};

export type MotionCategory = "idle" | "reaction" | "gesture" | "speech" | "locomotion" | "performance";

export type MotionChannelWeight = {
	channel: BehaviorChannel,
	/**  Semantic channel weight in permille, clamped by consumers to 0..=1000. */
	weight: number,
};

export type MotionEnabledUpdateRequest = {
	id: string,
	enabled: boolean,
};

export type MotionImportCommitRequest = {
	token: string,
	name: string,
	description: string,
	category: MotionCategory,
	playbackMode: MotionPlaybackMode,
	rootMode: MotionRootMode,
	interactionRegion?: InteractionRegion | null,
};

export type MotionImportInspection = {
	token: string | null,
	originalFileName: string,
	sizeBytes: number,
	sha256: string,
	durationMs: number,
	animatedBones: string[],
	fingerBoneCount: number,
	hasExpression: boolean,
	hasLookAt: boolean,
	warnings: string[],
};

export type MotionMetadataUpdateRequest = {
	id: string,
	name: string,
	description: string,
	category: MotionCategory,
	playbackMode: MotionPlaybackMode,
	rootMode: MotionRootMode,
};

export type MotionPlaybackMode = "once" | "loop" | "hold";

export type MotionRootMode = "discard" | "in_place" | "stage";

export type MotionRuntimeAsset = {
	entry: MotionCatalogEntry,
	assetUrl: string,
};

export type MotionSource = "builtin" | "user";

export type PetContextMenuRequest = {
	x: number | null,
	y: number | null,
};

export type PetTurnEvent = { type: "started"; runId: string } | { type: "text_delta"; runId: string; delta: string } | { type: "completed"; runId: string; text: string; speechQueued: boolean } | { type: "cancelled"; runId: string } | { type: "failed"; runId: string; code: string; message: string };

export type PetTurnRequest = {
	runId: string,
	text: string,
};

export type ReducedMotion = "system" | "on" | "off";

export type RequestId = string;

export type ResourceEntryRequest = {
	id: string,
};

export type ResourceImportRequest = {
	name: string,
};

export type RuntimeControllerKind = "cursor" | "drag" | "contact" | "root_motion" | "locomotion" | "speech";

export type RuntimeControllerRequest = {
	kind: RuntimeControllerKind,
	active: boolean,
	/**  Controller-specific normalized target. Locomotion currently consumes the X component. */
	target: [(number | null), (number | null), (number | null)],
	intensity: number | null,
	sequence: number,
};

export type Scope = "pet.interact" | "agent.run" | "settings.read" | "settings.write" | "llm.read" | "llm.write" | "llm.test" | "llm.chat" | "avatar.read" | "avatar.manage" | "avatar.runtime" | "motion.read" | "motion.manage" | "motion.runtime" | "voice.read" | "voice.manage" | "voice.playback" | "voice.capture" | "workbench.open" | "workbench.window" | "workspace.read" | "workspace.write" | "workspace.exec" | "browser.observe" | "browser.control" | "computer.observe" | "computer.control" | "connectors.invoke" | "devices.pair" | "admin.policy";

export type SpeechPlaybackEvent = {
	playbackId: string,
	runId: string | null,
	source: SpeechPlaybackSource,
	phase: SpeechPlaybackPhase,
	mediaPositionMs: number,
	durationMs: number,
	sequence: number,
	timeline: SpeechTimeline | null,
	segmentIndex: number,
	textStart: number,
	textEnd: number,
	/**
	 *  Display text is attached to Pet playback preparation so the WebView
	 *  can reveal the complete sentence when its PCM segment starts.
	 */
	displayText: string | null,
};

export type SpeechPlaybackPhase = "prepared" | "playing" | "progress" | "completed" | "stopped" | "failed";

export type SpeechPlaybackSource = "pet_turn" | "workbench_preview";

export type SpeechRecognitionRuntimeState = {
	installed: boolean,
	installing: boolean,
	bundled: boolean,
	modelName: string,
	provider: string,
	languages: string[],
	sizeBytes: number,
	computeMode: VoiceComputeMode,
	backend: VoiceComputeBackend | null,
	computeDevice: VoiceComputeDevice | null,
	fallbackReason: string | null,
	loading: boolean,
	error: string | null,
};

export type SpeechRecognitionSettingsInput = {
	computeMode: VoiceComputeMode,
};

export type SpeechTimeline = {
	frameDurationMs: number,
	jawOpen: number[],
	visemes: SpeechVisemeFrame[] | null,
	quality: SpeechTimelineQuality,
};

export type SpeechTimelineQuality = "energy_locked" | "phoneme_timed";

export type SpeechTurnEvent = {
	runId: string,
	phase: SpeechTurnPhase,
	message: string | null,
};

export type SpeechTurnPhase = "started" | "completed" | "stopped" | "skipped" | "failed";

export type SpeechVisemeFrame = {
	timeMs: number,
	aa: number,
	ih: number,
	ou: number,
	ee: number,
	oh: number,
};

export type ThemeMode = "light" | "dark" | "system";

export type ThemeProfile = {
	id: string,
	name: string,
	scheme: ThemeScheme,
	builtin: boolean,
	accent: string,
	background: string,
	foreground: string,
	uiFont: string,
	codeFont: string,
	translucentSidebar: boolean,
	contrast: number,
};

export type ThemeProfileDocument = {
	format: string,
	version: number,
	profile: ThemeProfile,
};

export type ThemeScheme = "light" | "dark";

export type VoiceCatalogSnapshot = {
	entries: VoiceModelEntry[],
	currentId: string,
};

export type VoiceComputeBackend = "direct_ml" | "cpu";

export type VoiceComputeDevice = {
	deviceId: number,
	name: string,
	dedicatedMemoryMb: number,
};

export type VoiceComputeMode = "auto" | "direct_ml" | "cpu";

export type VoiceImportCommitRequest = {
	token: string,
	name: string,
	licenseAcknowledged: boolean,
	speakerId: number,
};

export type VoiceModelEntry = {
	id: string,
	name: string,
	sha256: string,
	originalFileName: string,
	sizeBytes: number,
	origin: VoiceModelOrigin,
	modelType: string,
	languages: string[],
	sampleRate: number,
	speakerCount?: number,
	speakerId?: number,
	licenseSummary: string,
	licenseWarning: boolean,
	protected: boolean,
	importedAt: string,
};

export type VoiceModelInspection = {
	token: string | null,
	originalFileName: string,
	sizeBytes: number,
	sha256: string,
	modelType: string,
	languages: string[],
	sampleRate: number,
	speakerCount: number,
	suggestedSpeakerId: number,
	requiredFiles: string[],
	licenseSummary: string,
	licenseWarning: boolean,
	compatible: boolean,
	issues: string[],
};

export type VoiceModelOrigin = "built_in" | "imported";

export type VoiceRuntimeState = {
	available: boolean,
	muted: boolean,
	modelId: string | null,
	voiceName: string,
	speaking: boolean,
	speedPercent: number,
	provider: string,
	computeMode: VoiceComputeMode,
	backend: VoiceComputeBackend | null,
	computeDevice: VoiceComputeDevice | null,
	fallbackReason: string | null,
	loading: boolean,
	languages: string[],
	speakerCount: number,
	speakerId: number,
};

export type VoiceSettings = {
	muted: boolean,
	speedPercent?: number,
	computeMode?: VoiceComputeMode,
	/**  SenseVoice has its own session and can fall back independently from TTS. */
	recognitionComputeMode?: VoiceComputeMode,
};

export type VoiceSettingsInput = {
	speedPercent: number,
	computeMode: VoiceComputeMode,
};

export type WindowKind = "pet" | "settings" | "workbench";

export type WindowPlacementV1 = {
	x: number,
	y: number,
	width: number,
	height: number,
	monitorName: string | null,
	scaleFactor: number | null,
};

export type WorkbenchRoute = "home" | "settings/general" | "settings/appearance" | "settings/llm" | "settings/avatar" | "settings/motion" | "settings/voice" | "developer/motion-lab";

