import type { Page } from "@playwright/test";
import { resolve } from "node:path";
import { DEFAULT_APPEARANCE } from "../theme/context";

export const appearance = structuredClone(DEFAULT_APPEARANCE);

export const initialSettings = {
  schemaVersion: 9,
  developerMode: false,
  locale: "zh-CN",
  alwaysOnTop: true,
  petPlacement: null,
  llm: {
    baseUrl: "http://localhost:11434/v1",
    modelName: "gpt-5.6-sol",
    maxInputTokens: 1_050_000,
    maxOutputTokens: 128_000,
  },
  voice: { muted: false, speedPercent: 100, computeMode: "auto" },
  appearance,
};

export const motionEntry = {
  id: "builtin.clawatar.cute-standby.dda9b85c",
  source: "builtin",
  analysisStatus: "ready",
  protected: true,
  name: "Cute standby",
  nameZh: "可爱待机",
  description: "Clawatar idle",
  descriptionZh: "Clawatar 可爱待机",
  fileName: "dda9b85c992387e42eb07ad3a532364fd3a21be70e9311e18cf0619327d85b88.vrma",
  sha256: "dda9b85c992387e42eb07ad3a532364fd3a21be70e9311e18cf0619327d85b88",
  sizeBytes: 233136,
  durationMs: 6542,
  family: "idle",
  tags: ["idle", "cute"],
  loopMode: "loop",
  rootMode: "in_place",
  slot: "base",
  channelMask: ["full_body"],
  transitionProfileId: "idle.standard",
  fallbackMotionId: "builtin.openmaiwaifu.waiting.3b2e83e2",
  animatedBones: ["hips", "leftIndexProximal", "rightIndexProximal"],
  fingerBoneCount: 30,
  hasFingerMotion: true,
  hasExpression: false,
  hasLookAt: false,
  mirrorable: true,
  sourceProject: "Clawatar",
  sourcePaths: ["clawatar/public/animations/dm_24.vrma"],
  warnings: [],
};

const runtimeRequirements = [
  "vrm_format",
  "skinned_mesh",
  "complete_humanoid",
  "standard_blinks",
  "five_visemes",
  "standard_emotions",
  "look_at",
  "mtoon",
  "spring_bone",
  "spring_collider",
  "skin_weights",
  "resource_budget",
].map((requirement) => ({ requirement, passed: true, detail: "" }));

export const runtimeAssessment = {
  compatibility: "runtime_ready",
  detectorVersion: 4,
  capabilities: [
    "renderable_mesh",
    "skinned_mesh",
    "humanoid_skeleton",
    "blink",
    "viseme",
    "look_at",
    "spring_bone",
    "m_toon",
    "spring_bone_collider",
    "five_finger_hands",
    "five_visemes",
    "standard_expressions",
    "standard_motion_retarget",
    "runtime_ready",
  ],
  statistics: {
    nodeCount: 86,
    meshCount: 3,
    primitiveCount: 4,
    triangleCount: 42_800,
    materialCount: 9,
    textureCount: 12,
    boneCount: 67,
    animationCount: 0,
    morphTargetCount: 34,
    maxTextureDimension: 2048,
    estimatedTextureMemoryBytes: 100_663_296,
  },
  requirements: runtimeRequirements,
  issues: [],
};

export const workspaceGitFixture = {
  branch: "codex/workbench-layout",
  headSha: "a".repeat(40),
  statusFingerprint: "visual-status",
  detached: false,
  status: [],
  recentCommits: [],
};

export const workbenchEnvironmentFixture = {
  sessionId: "session-ui-unification",
  checkout: {
    id: "checkout-ui-unification",
    projectId: "project-hachimi",
    kind: "local",
    path: "D:\\workspace\\rust\\hachimi-code",
    baseRevision: null,
    headRevision: "a".repeat(40),
    status: "ready",
    pinned: false,
    createdAtMs: 1_774_184_400_000,
    updatedAtMs: 1_774_184_520_000,
  },
  workspace: null,
  bindingRevision: 4,
  baselineRevision: "9".repeat(40),
  changes: { changedFiles: 6, additions: 42, deletions: 13, truncated: false },
  git: {
    branch: "codex/workbench-layout",
    headSha: "a".repeat(40),
    detached: false,
    statusFingerprint: "visual-status",
    uncommittedFiles: 5,
    upstream: "origin/codex/workbench-layout",
    ahead: 2,
    behind: 0,
    defaultComparisonRef: "origin/main",
    refs: [
      { name: "codex/workbench-layout", revision: "a".repeat(40), remote: false, current: true },
      { name: "main", revision: "9".repeat(40), remote: false, current: false },
      { name: "origin/main", revision: "9".repeat(40), remote: true, current: false },
    ],
    remotes: [
      {
        name: "origin",
        displayUrl: "https://github.com/example/hachimi-code.git",
        remoteUrlHash: "b".repeat(64),
        forgeKind: "github",
      },
    ],
  },
  handoff: {
    localCheckoutId: "checkout-ui-unification",
    managedCheckoutId: "checkout-ui-worktree",
    canHandoff: true,
    blockedReason: null,
  },
  activities: [
    {
      kind: "browser",
      lease_id: "browser-lease-ui-unification",
      surface: "embedded",
      browser_tab_id: "browser-tab-ui-unification",
      browser_session_id: "browser-ui-unification",
      run_id: "run-ui-unification",
      domain: "learn.chatgpt.com",
    },
  ],
  sources: [
    {
      id: "source-upload-visual",
      sessionId: "session-ui-unification",
      runId: "run-ui-unification",
      kind: "upload",
      origin: "upload",
      attachmentId: "attachment-visual-notes",
      url: null,
      title: "notes.txt",
      browserTabId: null,
      createdAtMs: 1_774_184_500_000,
      lastUsedAtMs: 1_774_184_520_000,
    },
    {
      id: "source-browser-visual",
      sessionId: "session-ui-unification",
      runId: "run-ui-unification",
      kind: "web",
      origin: "browser",
      attachmentId: null,
      url: "https://learn.chatgpt.com/docs/environments/git-worktrees",
      title: "Git worktrees",
      browserTabId: "browser-tab-ui-unification",
      createdAtMs: 1_774_184_510_000,
      lastUsedAtMs: 1_774_184_530_000,
    },
  ],
  revision: 12,
  generatedAtMs: 1_774_184_530_000,
};

export const workspaceDiffFixture = {
  files: [
    {
      path: "packages/workbench/src/home.tsx",
      previousPath: null,
      status: "modified",
      additions: 24,
      deletions: 8,
      binary: false,
      tooLarge: false,
      hunks: [
        {
          header: "@@ -1148,4 +1148,6 @@",
          lines: [
            { kind: "context", oldLine: 1148, newLine: 1148, text: "<main>" },
            { kind: "deletion", oldLine: 1149, newLine: null, text: "<Toolbar />" },
            { kind: "addition", oldLine: null, newLine: 1149, text: "<ConversationToolbar />" },
          ],
        },
      ],
    },
  ],
  artifactId: null,
  truncated: false,
  generatedAtMs: 1_774_184_520_000,
};

export const workspaceFileChunkFixture = {
  path: "README.md",
  offset: 0,
  nextOffset: 73,
  byteSize: 73,
  eof: true,
  binary: false,
  utf8Text: "# Hachimi\n\nA local-first desktop workbench for reliable agent workflows.\n",
  dataBase64: "",
  etag: "readme-visual-etag",
};

export const directTerminalFixture = {
  id: "process-project-tools",
  sessionId: "session-ui-unification",
  runId: null,
  checkoutId: "checkout-ui-unification",
  runGeneration: null,
  ownerClientId: "window:workbench",
  commandSummary: "powershell.exe",
  interactive: true,
  status: "running",
  exitCode: null,
  outputLimitBytes: 2_097_152,
  createdAtMs: 1_774_184_520_000,
  updatedAtMs: 1_774_184_520_000,
  reconnectExpiresAtMs: 1_774_186_320_000,
};

const gestureEntry = {
  ...motionEntry,
  id: "builtin.clawatar.head-nod-yes.mock",
  name: "Head Nod Yes",
  nameZh: "点头同意",
  description: "A natural affirmative head nod.",
  descriptionZh: "自然的肯定点头动作。",
  family: "gesture",
  loopMode: "once",
  slot: "action",
  transitionProfileId: "action.standard",
  durationMs: 1800,
  fingerBoneCount: 0,
  hasFingerMotion: false,
};

export const taskScheduleFixtures = [
  {
    id: "schedule-daily-brief",
    name: "每日工作简报",
    enabled: true,
    prompt: "汇总今天的会议记录、未读消息和待办事项，生成一份简洁的工作简报。",
    schedule: { kind: "cron", expression: "0 0 9 * * 1-5", timezone: "Asia/Shanghai" },
    entryProfile: "workbench",
    workloadOverride: "office",
    contextTemplate: {
      kind: "workspace",
      workspace: { kind: "managed" },
      conversation_mode: "per_run_session",
    },
    skillAllowlist: [],
    mcpToolAllowlist: [],
    permissionPolicy: {
      level: "read_only",
      rules: {
        fileSystem: [],
        network: { enabled: false, hosts: [], protocols: [] },
        process: { spawn: false, interactive: false, allowedCommands: [] },
        browser: {
          observe: false,
          act: false,
          upload: false,
          download: false,
          cookieStorage: false,
          cdp: false,
          origins: [],
        },
        computer: { observe: false, act: false, allowedApplications: [], maxActions: null },
        mcp: [],
        connectors: [],
      },
      revision: 0,
    },
    permissionRevision: 1,
    timeoutMs: 120000,
    misfirePolicy: "skip",
    deliveryPolicy: "task_tab_only",
    configRevision: 2,
    createdBy: "user:visual",
    nextRunAtMs: Date.parse("2026-07-27T01:00:00.000Z"),
    health: "healthy",
    healthReason: null,
    createdAtMs: Date.parse("2026-07-20T01:00:00.000Z"),
    updatedAtMs: Date.parse("2026-07-26T14:30:00.000Z"),
  },
  {
    id: "schedule-project-review",
    name: "项目变更检查",
    enabled: false,
    prompt: "检查工作区最近的代码变更并整理需要关注的风险。",
    schedule: { kind: "cron", expression: "0 30 18 * * 5", timezone: "Asia/Shanghai" },
    entryProfile: "workbench",
    workloadOverride: "coding",
    contextTemplate: {
      kind: "workspace",
      workspace: { kind: "selected_directory", root_path: "D:\\workspace\\rust\\hachimi-code" },
      conversation_mode: "shared_session",
    },
    skillAllowlist: [],
    mcpToolAllowlist: [],
    permissionPolicy: {
      level: "read_only",
      rules: {
        fileSystem: [],
        network: { enabled: false, hosts: [], protocols: [] },
        process: { spawn: false, interactive: false, allowedCommands: [] },
        browser: {
          observe: false,
          act: false,
          upload: false,
          download: false,
          cookieStorage: false,
          cdp: false,
          origins: [],
        },
        computer: { observe: false, act: false, allowedApplications: [], maxActions: null },
        mcp: [],
        connectors: [],
      },
      revision: 0,
    },
    permissionRevision: 1,
    timeoutMs: 120000,
    misfirePolicy: "skip",
    deliveryPolicy: "task_tab_only",
    configRevision: 1,
    createdBy: "user:visual",
    nextRunAtMs: null,
    health: "needs_attention",
    healthReason: "项目授权需要更新",
    createdAtMs: Date.parse("2026-07-22T08:00:00.000Z"),
    updatedAtMs: Date.parse("2026-07-26T13:00:00.000Z"),
  },
];

export const taskRunFixtures = [
  {
    id: "task-run-daily-brief",
    scheduleId: "schedule-daily-brief",
    scheduleRevision: 2,
    trigger: "scheduled",
    scheduledForMs: Date.parse("2026-07-26T01:00:00.000Z"),
    invocationKey: "visual:daily-brief",
    requesterSessionId: null,
    executionSessionId: "session-ui-unification",
    runId: "run-ui-unification",
    permissionSnapshotHash: "visual-scope",
    status: "succeeded",
    progressPercent: 100,
    resultSummary: "工作简报已生成，共整理 4 项待办。",
    errorCode: null,
    errorSummary: null,
    artifactIds: [],
    deliveryStatus: "not_requested",
    deliveryErrorCode: null,
    createdAtMs: Date.parse("2026-07-26T01:00:00.000Z"),
    startedAtMs: Date.parse("2026-07-26T01:00:02.000Z"),
    finishedAtMs: Date.parse("2026-07-26T01:00:24.000Z"),
    updatedAtMs: Date.parse("2026-07-26T01:00:24.000Z"),
  },
];

export const runtimeMocks = {
  voiceRuntime: {
    available: true,
    muted: false,
    modelId: "builtin-melo-zh-en",
    voiceName: "Hachimi 中文女声",
    speaking: false,
    speedPercent: 100,
    provider: "sherpa_onnx_vits",
    computeMode: "auto",
    backend: "cpu",
    fallbackReason: null,
    loading: false,
    languages: ["zh-CN"],
    speakerCount: 1,
    speakerId: 0,
  },
  speechRecognition: {
    installed: true,
    installing: false,
    bundled: true,
    modelName: "SenseVoice-Small INT8",
    provider: "sherpa-onnx 1.13.4",
    languages: ["zh-CN", "en-US", "ja-JP", "ko-KR", "yue"],
    sizeBytes: 237_431_441,
    computeMode: "auto",
    backend: "direct_ml",
    fallbackReason: null,
    loading: false,
    error: null,
  },
  voices: {
    entries: [
      {
        id: "builtin-melo-zh-en",
        name: "Hachimi 中英双语女声（MeloTTS）",
        sha256: "e58351ed7149f290a54534538badd4077cdbe6fddc964b24d0bee870415d1514",
        originalFileName: "vits-melo-tts-zh_en.tar.bz2",
        sizeBytes: 167_006_755,
        origin: "built_in",
        modelType: "melo-vits",
        languages: ["zh-CN", "en-US"],
        sampleRate: 44_100,
        speakerCount: 1,
        speakerId: 0,
        licenseSummary: "MIT",
        licenseWarning: false,
        protected: true,
        importedAt: "0",
      },
    ],
    currentId: "builtin-melo-zh-en",
  },
  avatars: {
    entries: [
      {
        id: "mimi",
        name: "Mimi",
        originalFileName: "mimi.vrm",
        sizeBytes: 4096,
        sha256: "1234567890abcdef1234567890abcdef",
        importedAt: "1767225600000",
        isCurrent: true,
        format: "vrm0",
        assessment: runtimeAssessment,
      },
    ],
    currentId: "mimi" as string | null,
  },
  motions: {
    entries: [motionEntry, gestureEntry],
    transitionProfiles: [
      {
        id: "idle.standard",
        family: "idle",
        preferredDurationMs: 180,
        minimumDurationMs: 100,
        maximumDurationMs: 240,
        interruptPolicy: "safe_point",
        blendProfileId: "dead_blend.v1",
        syncGroup: null,
        entryWindows: [{ startMs: 0, endMs: 120 }],
        exitWindows: [],
        channelMask: ["full_body"],
      },
      {
        id: "action.standard",
        family: "gesture",
        preferredDurationMs: 150,
        minimumDurationMs: 80,
        maximumDurationMs: 240,
        interruptPolicy: "safe_point",
        blendProfileId: "dead_blend.v1",
        syncGroup: null,
        entryWindows: [{ startMs: 0, endMs: 120 }],
        exitWindows: [],
        channelMask: ["full_body"],
      },
      {
        id: "unknown.conservative",
        family: "unknown",
        preferredDurationMs: 200,
        minimumDurationMs: 120,
        maximumDurationMs: 280,
        interruptPolicy: "safe_point",
        blendProfileId: "dead_blend.v1",
        syncGroup: null,
        entryWindows: [{ startMs: 0, endMs: 120 }],
        exitWindows: [],
        channelMask: ["full_body"],
      },
    ],
    bindings: [] as Array<{
      region: string;
      motionId: string;
      cooldownMs: number;
      mirrorBySide: boolean;
    }>,
    disabledMotionIds: [] as string[],
  },
};

export const integrationMocks = {
  providers: [
    {
      id: "dingtalk",
      nameZh: "钉钉",
      nameEn: "DingTalk",
      iconAsset: "integration-icons/dingtalk.svg",
      transport: "stream",
      authMethod: "client_secret",
      capabilities: [
        "messaging",
        "dm",
        "group",
        "media_receive",
        "media_send",
        "proactive_delivery",
        "api_access",
      ],
      credentialFields: [
        { id: "clientId", label: "Client/App ID", kind: "text", required: true, capability: null },
        {
          id: "clientSecret",
          label: "Client/App Secret",
          kind: "secret",
          required: true,
          capability: null,
        },
        { id: "agentId", label: "Agent ID", kind: "text", required: false, capability: null },
        { id: "robotCode", label: "Robot Code", kind: "text", required: false, capability: null },
      ],
      sourceStatus: "official_sdk_reviewed",
    },
    {
      id: "feishu",
      nameZh: "飞书",
      nameEn: "Feishu",
      iconAsset: "integration-icons/feishu.svg",
      transport: "long_connection",
      authMethod: "client_secret",
      capabilities: [
        "messaging",
        "dm",
        "group",
        "topic",
        "media_receive",
        "media_send",
        "proactive_delivery",
        "api_access",
      ],
      credentialFields: [
        { id: "appId", label: "App ID", kind: "text", required: true, capability: null },
        { id: "appSecret", label: "App Secret", kind: "secret", required: true, capability: null },
      ],
      sourceStatus: "official_sdk_reviewed",
    },
    {
      id: "wecom_ai_bot",
      nameZh: "企微 AI Bot",
      nameEn: "WeCom AI Bot",
      iconAsset: "integration-icons/wecom.ico",
      transport: "web_socket",
      authMethod: "bot_secret",
      capabilities: [
        "messaging",
        "dm",
        "group",
        "media_receive",
        "media_send",
        "proactive_delivery",
      ],
      credentialFields: [
        { id: "botId", label: "Bot ID", kind: "text", required: true, capability: null },
        { id: "secret", label: "Secret", kind: "secret", required: true, capability: null },
      ],
      sourceStatus: "public_protocol_reviewed",
    },
    {
      id: "wecom_app",
      nameZh: "企微自建应用",
      nameEn: "WeCom custom app",
      iconAsset: "integration-icons/wecom.ico",
      transport: "encrypted_callback",
      authMethod: "callback_secret",
      capabilities: [
        "messaging",
        "dm",
        "media_receive",
        "media_send",
        "proactive_delivery",
        "api_access",
      ],
      credentialFields: [
        { id: "corpId", label: "Corp ID", kind: "text", required: true, capability: null },
        {
          id: "corpSecret",
          label: "Corp Secret",
          kind: "secret",
          required: true,
          capability: null,
        },
        { id: "agentId", label: "Agent ID", kind: "text", required: true, capability: null },
        {
          id: "callbackToken",
          label: "Callback Token",
          kind: "secret",
          required: true,
          capability: null,
        },
        {
          id: "encodingAesKey",
          label: "Encoding AES Key",
          kind: "secret",
          required: true,
          capability: null,
        },
        {
          id: "externalHttpsUrl",
          label: "External HTTPS URL",
          kind: "https_url",
          required: true,
          capability: null,
        },
      ],
      sourceStatus: "official_api_reviewed",
    },
    {
      id: "wechat_ilink",
      nameZh: "微信 iLink / ClawBot",
      nameEn: "WeChat iLink / ClawBot",
      iconAsset: "integration-icons/wechat-ilink.svg",
      transport: "qr_long_poll",
      authMethod: "qr_code",
      capabilities: ["messaging", "dm", "media_receive", "media_send", "qr_login"],
      credentialFields: [],
      sourceStatus: "public_qualification_unverified",
    },
  ],
  accounts: [
    {
      id: "wecom-app-support",
      displayName: "客户支持",
      providerId: "wecom_app",
      connectorAccountId: "wecom-app-support",
      channelAccountId: "wecom-app-support",
      tenantIdentityHash: "tenant-hash",
      transport: "encrypted_callback",
      state: "healthy",
      diagnostic: null,
      apiAccessEnabled: true,
      messagingEnabled: true,
      authorizations: [],
      credentialRevision: 2,
      configRevision: 3,
      updatedAtMs: 1_783_273_200_000,
    },
  ],
  gatewayHealth: {
    running: true,
    state: "ready",
    lastHeartbeatMs: 1_783_273_200_000,
    lastStartedAtMs: 1_783_273_199_000,
    restartAttempt: 0,
    lastErrorCode: null,
    channels: ["dingtalk", "feishu", "wecom_ai_bot", "wecom_app", "wechat_ilink"],
    pendingIngress: 0,
    pendingDeliveries: 0,
    revision: 8,
  },
};

export const hostSettingsMocks = {
  list_installed_plugins: [],
  list_installed_plugin_contributions: [],
  list_connector_accounts: [],
  list_integration_providers: integrationMocks.providers,
  list_enterprise_integrations: integrationMocks.accounts,
  get_session_permission_config: {
    policy: {
      level: "read_only",
      rules: {
        fileSystem: [],
        fileSystemUnrestrictedRead: false,
        fileSystemUnrestrictedWrite: false,
        network: {
          enabled: false,
          unrestrictedHosts: false,
          hosts: [],
          protocols: [],
        },
        process: {
          spawn: false,
          interactive: false,
          unrestrictedCommands: false,
          allowedCommands: [],
        },
        browser: {
          observe: false,
          act: false,
          upload: false,
          download: false,
          cookieStorage: false,
          cdp: false,
          unrestrictedOrigins: false,
          origins: [],
        },
        computer: {
          observe: false,
          act: false,
          unrestrictedTargets: false,
          allowedApplications: [],
          maxActions: null,
        },
        mcp: [],
        connectors: [],
      },
      revision: 0,
    },
    skillIds: [],
    extraAuthorizations: [],
  },
  get_gateway_health: integrationMocks.gatewayHealth,
  get_runtime_health: {
    components: [
      "gateway",
      "internal_resources",
      "mcp",
      "scheduler",
      "browser_extension",
      "cef",
      "computer_use",
    ].map((component) => ({
      component,
      state: "ready",
      errorCode: null,
      retryable: false,
      attempt: 0,
      nextRetryAtMs: null,
      updatedAtMs: 1_783_273_200_000,
    })),
    revision: 1,
  },
  get_channel_access_policy: {
    accountId: "wecom-app-support",
    dmPolicy: "pairing",
    allowlistActorIds: [],
    grantCeiling: {
      permissionPolicy: {
        level: "read_only",
        rules: {
          fileSystem: [],
          network: { enabled: false, hosts: [], protocols: [] },
          process: { spawn: false, interactive: false, allowedCommands: [] },
          browser: {
            observe: false,
            act: false,
            upload: false,
            download: false,
            cookieStorage: false,
            cdp: false,
            origins: [],
          },
          computer: { observe: false, act: false, allowedApplications: [], maxActions: null },
          mcp: [],
          connectors: [],
        },
        revision: 0,
      },
      skillIds: ["documents", "spreadsheets"],
      mcpServerIds: [],
      connectorSelections: [],
      readOnlyWorkspaceRoots: [],
      networkHosts: [],
    },
    revision: 2,
  },
};

export async function installMotionLabAssets(page: Page) {
  await page.route("http://hachimi-avatar.localhost/mimi", (route) =>
    route.fulfill({
      path: resolve(
        import.meta.dirname,
        "../../../../assets/avatar-default/2639776812528692620/2639776812528692620.vrm",
      ),
      contentType: "model/gltf-binary",
    }),
  );
  await page.route("http://hachimi-motion.localhost/builtin/*.vrma", (route) =>
    route.fulfill({
      path: resolve(
        import.meta.dirname,
        `../../../../assets/avatar-motions-v5/builtin/${motionEntry.fileName}`,
      ),
      contentType: "model/gltf-binary",
    }),
  );
}
